version: '3.9'

services:
  server:
    build: .
    ports: 
      - "8081:8080"
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: