version: '3.9'

services:
  server:
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - .env
    command: >
      sh -c "npx sequelize-cli db:create && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start"
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
