name: Render CI/CD Tool

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Debug Database URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "URL Structure Check (sanitized):"
          echo $DATABASE_URL | sed 's/:[^:@]*@/:*****@/'
          echo "Protocol Check:"
          echo $DATABASE_URL | cut -d: -f1
          
      - name: Debug Secrets Availability
        run: |
          echo "Checking secret availability..."

           # Check DATABASE_URL
          if [ -n "${{ secrets.DATABASE_URL }}" ]; then
            echo "✅ DATABASE_URL is available"
            echo "URL format check:"
            if [[ ${{ secrets.DATABASE_URL }} == postgresql://* ]]; then
              echo "✅ URL format appears correct"
            else
              echo "❌ URL format might be incorrect"
            fi
          else
            echo "❌ DATABASE_URL is NOT available"
          fi
      
      - name: Build project
        working-directory: ./src
        run: npm run build

      - name: Build project
        working-directory: ./src
        run: npm run build

      - name: Deploy to Render
        uses: givemomentum/render-deploy@main
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: false
          wait_deploy: false
          github_deployment: false
          deployment_environment: 'development'

      - name: Notify deployment success
        if: success()
        run: echo "Deployment succeeded!"
